version: '3'

services:

    galhardo_finances_postgres:
        image: postgres
        container_name: galhardo_finances_postgres
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "2222:5432"
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - galhardo_finances_network

    # system: postgresql | username: postgres | password: postgres |server: galhardoapp_api_postgres
    galhardoapp_api_adminer:
        image: adminer
        container_name: galhardoapp_api_adminer
        ports:
            - "8080:8080"
        networks:
            - galhardo_finances_network

networks:
    galhardo_finances_network:
        driver: bridge

volumes:
    postgres-data: null
